[package]
name = "ULifeLib"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["staticlib", "lib"]
name = "ULifeLib"

[dependencies]
prost = "0.14.1"
reqwest = "0.12.24"
uniffi = "0.30"
